name: Python Pull Request Workflow
on: [pull_request]
jobs:
  test:
    name: Quality Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
      - name: Run unit tests
        run: |
          pip install pytest
          pytest
      - name: Wemake Python Style Guide
        uses: wemake-services/wemake-python-styleguide@0.14.1
        continue-on-error: true
        with:
          reporter: 'github-pr-review'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - users: actions/checkout@v2
      - name: Build Image
        run: docker build -t wratt-bot .
